# Generated by Django 4.1.13 on 2024-05-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('su_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('selling_price', models.CharField(max_length=100)),
                ('mrp', models.CharField(max_length=100)),
            ],
        ),
    ]
