# Generated by Django 4.1.13 on 2024-06-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('su_admin', '0002_order_products_review_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_code',
            field=models.CharField(default=None, max_length=20, unique=True),
        ),
    ]
