# Generated by Django 4.1.13 on 2024-06-03 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('su_admin', '0003_alter_products_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('qty', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('total', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('discount', models.CharField(default=None, max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='su_admin.products')),
            ],
        ),
    ]
