# Generated by Django 4.1.13 on 2024-06-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('su_admin', '0003_alter_order_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_code',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
