# Generated by Django 4.1.13 on 2024-06-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('su_admin', '0004_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_items',
            name='order_code',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
