# Generated by Django 4.1.13 on 2024-06-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('su_admin', '0006_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='review',
            name='message',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
