# Generated by Django 4.1.13 on 2024-06-03 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('su_admin', '0007_review_status_alter_review_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(default=None, max_length=255)),
                ('user_id', models.CharField(default=None, max_length=255)),
                ('delivery_address', models.CharField(default=None, max_length=255)),
                ('order_total', models.CharField(default=None, max_length=255)),
                ('status', models.CharField(default=None, max_length=255)),
                ('date', models.DateField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='su_admin.order_items')),
            ],
        ),
    ]
