# Generated by Django 4.1.13 on 2024-06-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('su_admin', '0008_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
